Remove broken tests
The exception we have is:
NameError: undefined local variable or method `failed_servce'
Because we are not talking to a real Puppet service.

While here, macke sure all tests in all test files are run by finxing
the test filename.